@echo on
CD ..
SET ROOT_FOLDER_PATH=%CD%
SET SOURCE_FOLDER_PATH=%ROOT_FOLDER_PATH%\src
SET SERVERS_FOLDER_NAME=%ROOT_FOLDER_PATH%\Public
SET MYSQL_HOME=%ROOT_FOLDER_PATH%\Public\mysql\
SET MYSQL_ZIP_NAME=mysql.zip.001
SET FLYWAY_FOLDER_PATH=%ROOT_FOLDER_PATH%\Public\flyway-2.3
SET FLYWAY_ZIP_PATH=flyway.zip
SET APACHE_FOLDER_PATH=%ROOT_FOLDER_PATH%\Public\Apache24
SET APACHE_ZIP_PATH=apache.zip
SET PHP_FOLDER_PATH=%ROOT_FOLDER_PATH%\Public\php
SET PHP_ZIP_PATH=php5.6.zip

xcopy /S /Y "%SOURCE_FOLDER_PATH%" "%APACHE_FOLDER_PATH%\htdocs"

cd scripts